---
- name: Submit DB2 batch job to execute a query 
  hosts: zos
  gather_facts: false
  environment: "{{ environment_vars }}"

  vars:
    job_owner: IBMUSER
    db2_subsystem: DBD1
    sql: |
      SELECT CREATOR AS METRIC,
             COUNT(*) AS VALUE
      FROM SYSIBM.SYSTABLES
      GROUP BY CREATOR;

  tasks:
  
  - name: Create SQL job
    template:
      src: templates/db2_query.jcl.j2
      dest: /tmp/db2_query.jcl
    delegate_to: localhost  

  - name: Submit job
    ibm.ibm_zos_core.zos_job_submit:
      src: /tmp/db2_query.jcl
      remote_src: false
      wait_time: 60
    register: job

  - name: Dump output
    debug:
      msg: "{{ job }}"
